#spring.application.name=Agensy-House

spring:
  datasource:
      url: jdbc:postgresql://localhost:5432/java16
      username: postgres
      password: Aibek005
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
server:
  port: 8888


  #spring.application.name=TEST-1
#
#  spring:
#    datasource:
#      url: jdbc:postgresql://localhost:5432/pop
#      username: postgres
#      password: Aibek005
#    jpa:
#      show-sql: true
#      hibernate:
#        ddl-auto: update
#
#  server:
#    port: 8081
#

