#spring.application.name=Agensy-House

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/java16
    username: postgres
    password: Aibek005

  security:
      jwt:
        secret_key: java16mukhammedurmatpeaksoft
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
server:
  port: 8888


  error:
    include-message: always


  #spring.application.name=TEST-1
#
#  spring:
#    datasource:
#      url: jdbc:postgresql://localhost:5432/pop
#      username: postgres
#      password: Aibek005
#    jpa:
#      show-sql: true
#      hibernate:
#        ddl-auto: update
#
#  server:
#    port: 8081
#

